Add searchbar to home
gopher-tunnels/gt-front-end pull request #43
Opened 2024-07-13 22:08 UTC by Whatshisname303

2024-07-13 23:09 UTC, VicHofs commented
Hey Alex, thanks for the PR! Here are a few issues to fix before merging:
- [ ] Fix the dismissal logic (can't tap out of the toggled state)

- [ ] Include the "glow" styles on toggle:
<img width="485" alt="image" src="https://github.com/user-attachments/assets/5160336d-0c5e-4b46-8705-7166623aeb8e">

- [ ] Modify the colors from hard-coded to theme-provided values:
![image](https://github.com/user-attachments/assets/518e070f-b038-495a-992b-24c33ec56316)

- [ ] Create the search result components and a prop to pass that data to the searchbar:
<img width="473" alt="image" src="https://github.com/user-attachments/assets/3d9555c8-6568-4c52-a116-0fd0e5a21d9a">

2024-07-13 23:19 UTC, VicHofs commented on components/Searchbar/index.tsx
> +                    borderColor: isFocused ? "#7A0019" : "#BC808C",
Use theme-provided colors

2024-07-13 23:23 UTC, VicHofs requested changes
Hey Alex, thanks for the PR! Here are a few issues to fix before merging:
- [x] Fix the dismissal logic (can't tap out of the toggled state)

- [x] Include the "glow" styles on toggle:
<img width="485" alt="image" src="https://github.com/user-attachments/assets/5160336d-0c5e-4b46-8705-7166623aeb8e">

- [x] Modify the colors from hard-coded to theme-provided values:
![image](https://github.com/user-attachments/assets/518e070f-b038-495a-992b-24c33ec56316)

- [ ] Create the search result components and a prop to pass that data to the searchbar:
<img width="473" alt="image" src="https://github.com/user-attachments/assets/3d9555c8-6568-4c52-a116-0fd0e5a21d9a">

- [ ] Change the color of the caret in the input from the default to a theme color:
![image](https://github.com/user-attachments/assets/cf81e5fe-b1b4-4777-abd7-dc4279ff3608)

2024-07-13 23:23 UTC, VicHofs commented on components/Searchbar/index.tsx
> +                    placeholderTextColor="#AB5E6E"
Use theme-provided colors

2024-07-13 23:23 UTC, VicHofs commented on components/Searchbar/index.tsx
> +                <SearchInput
Set caret color to a theme color instead of the default

2024-07-13 23:23 UTC, VicHofs commented on components/Searchbar/index.tsx
> +                    borderColor: isFocused ? "#7A0019" : "#BC808C",
Use theme-provided colors

2024-07-13 23:23 UTC, VicHofs commented on components/Searchbar/styles.ts
> +export const Container = styled.View`
Don't position this absolutely yourself! There is a `Content` component in `Home` that exists precisely for the purpose of absolutely-positioning these overlay elements over the map view.

2024-07-16 14:36 UTC, Whatshisname303 commented
### Shadows
Android and IOS have different ways of managing shadows that I tried to mash together in the CSS. For some reason custom colors didn't work, and I couldn't get it to look right in general. I also don't have any way of testing IOS so would be good to have someone else look at that.

Found a package `react-native-drop-shadow` although it makes images and says it's harder on resources so I didn't decide to use it yet.

### Dismissal logic
I couldn't figure out how to get the search-bar to lose focus while tapping outside the search-bar without making a view cover the rest of the screen which I read is a bad idea, although it works if you're tapping on some other element.

I don't know exactly what actions should dismiss the focus so I just added in the obvious ones that worked easily for now
- Keyboard back button
- Keyboard submit button
- Tapping something in the dropdown

### Other
There were some colors I couldn't find in the theme so I left them hardcoded
- unfocused search-bar border: #bc808c 
- shadow color: #ffe9b9 

Search results are hard coded template data right now rather than props. Also seems like it might be better to handle it all within the component rather than passing anything around.

2024-07-16 18:16 UTC, VicHofs requested changes
Hey Alex, thanks for reviewing your PR! There's still a few things left to fix before merging, summarized below:

### Shadows
You can do this without packages; look at [this article](https://blog.logrocket.com/applying-box-shadows-in-react-native/) for reference. Alternatively, feel free to use any libraries you deem adequate!

### Dismissal logic
There is already a View on top of everything; it's the `Content` component I mentioned before. Currently, it has a prop set to ignore all taps, but you can also use a different value and pass-through taps to the map while still reacting to that same event. The dismissal is fine as-is right now, though. **Do make sure the results container is not visible if there are no results to display.**

### Other
- [ ] Move the `ScrollView` inside the View containing the results; you can scroll the whole search bar out of view at the moment
- [x] Add the missing magnifying glass icon on the left
- [ ] Add a 'tapped' state to the search result components
- [x] Add missing building icons in the search result components

_See more comments in the code review!_

2024-07-16 18:18 UTC, VicHofs commented on components/Searchbar/index.tsx
> +                        shadowColor: isFocused ? "#FFE9B9" : "rgba(0,0,0,0)",
If your reference is using colors outside the theme, use the most similar color to each in the theme instead

2024-07-16 18:19 UTC, VicHofs commented on components/Searchbar/index.tsx
> +const TEMP_BUILDINGS = [
You can leave this data commented somewhere if you'd like to make it easy to test, though

2024-08-11 18:52 UTC, Whatshisname303 commented
- Still couldn't figure out shadows
- Don't know what adding tapped state to search result means
- Still got an underline passing refs to styled components

Things should otherwise be working

2024-08-17 19:36 UTC, merged